POST http://localhost:3000/regtCars/Ncr
content-type: application/json

{
    "platNo": "3AA452352",
    "driverName": "YFRH TREJ",
     "model": "Toyota Yaris",
     "capacity": 3,
     "carStat": 1
}

###

GET  http://localhost:3000/regtCars

###

GET  http://localhost:3000/regtCars/byId/63dcd375c872072be16ab8aa

###

GET  http://localhost:3000/regtCars/plats/3AAB09887


###

GET  http://localhost:3000/regtCars/dropdown