### 
        ### Start Car
###

POST http://localhost:5000/regtCars/Ncr
content-type: application/json

{
    "platNo": "3AA73596",
    "driverName": "HTTR EFYXZ",
     "model": "Yaris",
     "capacity": 4,
     "dirverPhone": "251975649622"
}

###

GET  http://localhost:5000/regtCars

###

GET  http://localhost:5000/regtCars/byId/63dcd375c872072be16ab8aa

###

GET  http://localhost:5000/regtCars/plats/3AA80051


###

Put http://localhost:5000/regtCars/updateCar/64ed912fbd16e6c7ec6dc498
content-type: application/json

{
    "platNo": "3AAB12587",
    "driverName": "HTTR EFYXZ",
     "model": "Yaris",
     "capacity": 4,
     "dirverPhone": "251975649322",
     "carStat": 1
}

###

GET  http://localhost:5000/regtCars/dropdown


### 
        ### END Car
        ### Start Reservation
###

POST http://localhost:5000/reservation/Nrs
content-type: application/json

{
     "dts": "18-09-2023",
    "requster": "SBVMNDFB FTEBDgvnD",
     "depmnt": "Security",
     "frm": "New shop",
     "_to": "Head office",
     "tm_frm": "7:00",
     "tm_to": "9:30",
     "dsc": "Training",
     "userName": "user1" 
}


###

GET  http://localhost:5000/reservation/

###

GET  http://localhost:5000/reservation/byStat/2

###

GET  http://localhost:5000/reservation/byUser/user1

###

GET  http://localhost:5000/reservation/byUser/user1/3

###


GET  http://localhost:5000/reservation/byDepr/Information Technology

###

GET  http://localhost:5000/reservation/byId/64f8293664fad0ea5b63fdb1

###

Put http://localhost:5000/reservation/update/6507a216678e632c9d8c9bf4
content-type: application/json

{
    "dts": "18-08-2023",
    "requster": "YIUY Uytr",
     "depmnt": "Salse",
     "frm": "Head Office",
     "_to": "New Shop",
     "dsc": "Promoting New Shop",
     "reqStat": 1,
     
}

###

Put http://localhost:5000/reservation/uptStus/6507a216678e632c9d8c9bf4
content-type: application/json

{
     "reqStat": 0
}

###

### 
        ### END Resvation
        ### Start User
###

POST http://localhost:5000/users/sigUp
content-type: application/json

{
    "firstName": "Kteyet",
    "lastName": "Ykuttr",
    "departmnt": "Security",
    "email": "KteyetYkuttr@gmail.com",
    "userName": "sctDep",
    "passWord": "sctDep", 
    "userRole": 2
}



###

GET  http://localhost:5000/users/all


###

GET  http://localhost:5000/users/logIn/tcerT1/hghyXxhbABc


###

POST http://localhost:5000/users/logIn
content-type: application/json

{
    
    "userName": "user2",
    "passWord": "user2"
    
}

###

Put http://localhost:5000/users/update/64ef05cf7f8729e2d4eba684
content-type: application/json

{
    "firstName": "AbcEF",
    "lastName": "Abcd",
    "departmnt": "Information Technology",
    "email": "stevegoodmane@gmail.com",
    "userName": "user3",
    "passWord": "user3", 
    "userRole": 2
}